Multiple runner support
utm-cssc/codetierlist pull request #36
Opened 2023-12-10 21:30 UTC by ggggg

Codetierlist will now have support for multiple runners

2023-12-10 21:31 UTC, ggggg commented on backend/src/common/runner/index.ts
> +];
@DakshChan this is how we will add new images

2023-12-10 22:20 UTC, logonoff requested changes

2023-12-10 22:20 UTC, logonoff commented on frontend/pages/courses/[courseID]/admin/create_assignment/index.tsx
> -                    <br /><br />
use CSS

2023-12-10 22:20 UTC, logonoff commented on frontend/pages/courses/[courseID]/admin/create_assignment/index.tsx
> +                    <Label htmlFor="runner">Runner image:</Label><br/>
maybe add an explainer

2023-12-10 23:11 UTC, ggggg commented on frontend/pages/courses/[courseID]/admin/create_assignment/index.tsx
> -                    <br /><br />
This was there before

2023-12-10 23:11 UTC, ggggg commented on frontend/pages/courses/[courseID]/admin/create_assignment/index.tsx
> +                    <Label htmlFor="runner">Runner image:</Label><br/>
like a tooltip?

2023-12-11 01:06 UTC, logonoff commented on frontend/pages/courses/[courseID]/admin/create_assignment/index.tsx
> +                    <Label htmlFor="runner">Runner image:</Label><br/>
that works

2023-12-11 01:06 UTC, logonoff commented on frontend/pages/courses/[courseID]/admin/create_assignment/index.tsx
> -                    <br /><br />
worry werid

2023-12-11 17:32 UTC, logonoff approved these changes

2023-12-11 17:32 UTC, merged