add main deploy
utm-cssc/codetierlist pull request #6
Opened 2023-10-28 20:42 UTC by logonoff

Using the types package

2023-10-28 21:07 UTC, Yousef-Bulbulia approved these changes

2023-10-28 21:13 UTC, ggggg requested changes

2023-10-28 21:13 UTC, ggggg commented on .github/workflows/devdeploy.yml
> +          docker builder prune -f
This is just a white space change? Shouldn't we keep the trailing line anyhow?

2023-10-28 21:13 UTC, ggggg commented on frontend/components/AssignmentCard/AssignmentCard.tsx
> +import { type DisplayTier, type Tier } from '../../../backend/src/types/global';
Not how types are handled, import from type package

2023-10-28 21:13 UTC, ggggg commented on frontend/components/Navbar/Navbar.tsx
> +    const user = { utorid: "michael", email: "liut" };
Assuming this is mock data for now, should add a central function like `getUser` so it is easier to integrate in the future

2023-10-28 21:13 UTC, ggggg commented on frontend/tsconfig.json
> +  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts", "pages/courses/index.tsx", "../frontend/pages/404.tsx"],
Not sure why pages need to be included explicitly

2023-10-28 21:24 UTC, ggggg approved these changes

2023-10-30 20:32 UTC, ggggg commented on frontend/pages/courses/[courseID]/[assignmentID]/page.module.css
Empty file?

2023-11-05 06:07 UTC, merged